#!/usr/bin/env python3
"""backlog.py — regenerate BACKLOG.md from FINDINGS-LEDGER.md (one line per open row, grouped by status).
The status is the LAST cell (from the 6th on) that starts with a status word: rows have 8–10 columns and cells
may hold pipes, so counting from the front misreads them (2026-09-29: the first generator put 17 finished rows in "open")."""
import collections, datetime, re, sys
base = sys.argv[1] if len(sys.argv) > 1 else 'local-edition/mlx/quality'
rows = []
for l in open(f'{base}/FINDINGS-LEDGER.md'):
    m = re.match(r'\| (Q-\d+) ', l)
    if not m: continue
    c = [x.strip() for x in l.rstrip().rstrip('|').split(' | ')]
    rows.append((m.group(1), c[3] if len(c) > 3 else '', c[4] if len(c) > 4 else '', c[-1] if l.rstrip().endswith('|') is False else c[-1], c))
def status(c): return c[-1].lower() if not c[-1] else c[-1].lower()
groups = collections.OrderedDict((k, []) for k in ('cutting / open / framed', 'queued / scheduled', 'awaiting live prove', 'parked'))
done = collections.Counter()
STATUS = re.compile(r'(fixed|shipped|proven|pass|refuted|dropped|obsolete|parked|queued|scheduled|cutting|open|framed|reopened|awaiting|live)\b', re.I)
def status_cell(c):
    # The header is id·date·track·surface·finding·scenario·verdict·STATUS·note → field 7 (0-based). A row with a
    # pipe inside an earlier cell shifts it to 8. The note may itself start with a status-like word ("open the
    # created session"), so only fields 7 and 8 are candidates, in that order.
    for i in (7, 8, 6):
        if i < len(c) and STATUS.match(c[i].strip()): return c[i].strip()
    return c[7].strip() if len(c) > 7 else c[-1].strip()
for q, surface, finding, _, c in rows:
    st_cell = status_cell(c); s = st_cell.lower()
    if 'proven live' in s or s.startswith(('proven', 'pass')): done['proven / pass'] += 1
    elif s.startswith(('refuted', 'dropped', 'obsolete')): done['refuted / dropped'] += 1
    elif s.startswith('shipped (') : done['shipped (feature)'] += 1
    elif s.startswith('parked'): groups['parked'].append((q, surface, finding, st_cell))
    elif s.startswith(('queued', 'scheduled')): groups['queued / scheduled'].append((q, surface, finding, st_cell))
    elif 'awaiting' in s or s.startswith(('fixed', 'shipped')): groups['awaiting live prove'].append((q, surface, finding, st_cell))
    else: groups['cutting / open / framed'].append((q, surface, finding, st_cell))
now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')
out = ['# MLX quality loop — BACKLOG (generated by harness/backlog.py from FINDINGS-LEDGER.md; do not hand-edit)', '',
       f'Updated {now}. Rows {len(rows)}: ' + ' · '.join(f'{k} {v}' for k, v in done.items()) + ' · ' +
       ' · '.join(f'{k} {len(v)}' for k, v in groups.items()), '']
for g, items in groups.items():
    out.append(f'## {g} ({len(items)})')
    out += [f'- {q} · {s[:60]} — {f[:100]} · _{st[:90]}_'.replace('\n', ' ') for q, s, f, st in items]
    out.append('')
open(f'{base}/BACKLOG.md', 'w').write('\n'.join(out))
print(out[2])
