import { describe, it, expect } from 'vitest';
import {
  PERSONA_USER_MARKER,
  isPersonaPath,
  isEditable,
  splitPersona,
  recomposePersona,
  skillOrigin,
} from './skillKinds';

/** A persona as the Rust `render_persona_skill` actually emits one — banner and all. */
const RENDERED = [
  '---',
  'name: stack-fastapi',
  'description: What goose learned from builds of the fastapi stack that actually shipped.',
  '---',
  '',
  '# fastapi',
  '',
  'Written by goose after a build of this stack that **built and verified**.',
  '',
  'Learned from **2** successful build(s).',
  '',
  `> **Correcting this file:** everything down to the \`${PERSONA_USER_MARKER}\` heading is REGENERATED by`,
  `goose after the next successful build of this stack, so a fix typed up here is lost. Write it under`,
  `\`${PERSONA_USER_MARKER}\` instead — that section is kept word for word.`,
  '',
  '## What worked',
  '',
  'Use uvicorn with --reload in dev.',
  '',
  '---',
  '_footer_',
  '',
  PERSONA_USER_MARKER,
  '',
  'We use SQLModel here, NOT raw SQLAlchemy.',
  '',
].join('\n');

describe('isPersonaPath', () => {
  it('matches what the engine writes and nothing else', () => {
    expect(isPersonaPath('/Users/x/.config/goose/skills/stack-fastapi')).toBe(true);
    expect(isPersonaPath('/Users/x/.config/goose/skills/stack-react-vite-ts')).toBe(true);
    expect(isPersonaPath('/Users/x/.config/goose/skills/stack-fastapi/')).toBe(true);
    // a human's own skill, even one about a stack
    expect(isPersonaPath('/Users/x/.agents/skills/fastapi-tips')).toBe(false);
    expect(isPersonaPath('/Users/x/.agents/skills/my-stack-notes')).toBe(false);
    expect(isPersonaPath('builtin://skills/developer')).toBe(false);
  });
});

describe('isEditable', () => {
  it('refuses built-ins regardless of the writable flag', () => {
    // skills/mod.rs hardcodes writable:true and builtin_skill_entry never clears it, so the flag is a lie —
    // trusting it would offer an editor the backend rejects in require_mutable_type.
    expect(isEditable({ type: 'builtinSkill' })).toBe(false);
    expect(isEditable({ type: 'skill' })).toBe(true);
  });
});

describe('splitPersona', () => {
  it('cuts at the HEADING, not at the banner that names it', () => {
    const { engine, notes } = splitPersona(RENDERED);
    // The banner mentions the marker twice before the real heading exists. Splitting on the first textual
    // hit would hand goose's own lesson back as "the user's notes" and compound it on every rewrite.
    expect(RENDERED.split(PERSONA_USER_MARKER).length - 1).toBeGreaterThan(1);
    expect(notes).toBe('We use SQLModel here, NOT raw SQLAlchemy.');
    expect(engine).toContain('## What worked');
    expect(engine).toContain('Use uvicorn with --reload in dev.');
    expect(engine).not.toContain('SQLModel');
  });

  it('reports notes:null for a skill with no notes section', () => {
    const plain = '---\nname: mine\n---\n\nJust a normal hand-written skill.\n';
    expect(splitPersona(plain)).toEqual({ engine: plain, notes: null });
  });
});

describe('recomposePersona', () => {
  it('round-trips without touching the engine region', () => {
    const { engine, notes } = splitPersona(RENDERED);
    const out = recomposePersona(engine, notes ?? '');
    const again = splitPersona(out);
    expect(again.notes).toBe(notes);
    expect(again.engine.trim()).toBe(engine.trim());
  });

  it('never grows a second notes section', () => {
    const { engine } = splitPersona(RENDERED);
    let doc = recomposePersona(engine, 'first');
    doc = recomposePersona(splitPersona(doc).engine, 'second');
    doc = recomposePersona(splitPersona(doc).engine, 'third');
    const headings = doc.split(`\n${PERSONA_USER_MARKER}`).length - 1;
    expect(headings).toBe(1);
    expect(splitPersona(doc).notes).toBe('third');
  });

  it('keeps the user text byte-exact, including markdown that looks like a heading', () => {
    const { engine } = splitPersona(RENDERED);
    const tricky = '## What worked\n\nno: THIS is my correction, and it starts with a heading.';
    const out = recomposePersona(engine, tricky);
    expect(splitPersona(out).notes).toBe(tricky);
  });
});

describe('skillOrigin', () => {
  it('separates the four kinds a reader has to tell apart', () => {
    expect(skillOrigin({ type: 'builtinSkill', path: 'builtin://skills/x', global: true })).toBe(
      'builtin'
    );
    expect(skillOrigin({ type: 'skill', path: '/c/skills/stack-fastapi', global: true })).toBe(
      'persona'
    );
    expect(skillOrigin({ type: 'skill', path: '/h/.agents/skills/mine', global: true })).toBe(
      'global'
    );
    expect(skillOrigin({ type: 'skill', path: '/proj/.goose/skills/mine', global: false })).toBe(
      'project'
    );
  });
});
