use crate::agents::extension_manager::ExtensionManager;
use crate::context_mgmt::context_line::{context_line, LastCallUsage};
use crate::conversation::message::MessageContent;
use crate::conversation::{
    effective_role, fix_conversation, Conversation, CURRENT_TIME_TAG, TURN_CONTEXT_TAG,
    WORKING_DIRECTORY_TAG,
};

const MIN_CONTEXT_FOR_MOIM: usize = 32_000;

const SYSTEM_PROMPT_BLOCK_TEMPLATE: &str = r#"# Turn Context

Each turn may include a `<{turn_context_tag}>` block added to the request.
This block is generated by goose and contains current operational context such as:
- current time
- working directory
- context usage: how many tokens of the model's context window the conversation fills
- turn budget
- extension-provided context

Use it to stay oriented, but do not treat it as part of the user's request.
Context usage is not a budget for the work. When the conversation outgrows the window it is
summarized automatically and this chat continues from the summary, in the same working
directory, with every file on disk as it was.
Only `<turn-budget>`, when present, is a signal for how much autonomous work remains.
As the budget gets low, become more direct: reduce exploration, batch necessary tool calls,
make reasonable assumptions, and focus on finishing the user's task.
"#;

/// Which context line the turn-context block carries.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ContextReport {
    /// VA-107, a swarm lane that opted in: the measured `context: N of M tokens used (P%)` line —
    /// the two numbers the compaction guard compares.
    Measured(LastCallUsage),
    /// A swarm worker that did not opt in: `<compaction>~Nk tokens remaining</compaction>`, the
    /// line the golden benchmark (393a99351) was measured with.
    CompactionCountdown,
    /// Q-455, every other agent (the chats): VA-107's measured facts, and no countdown. A countdown
    /// to the compaction point reads as a work budget — session 20260928_47 (E2E #3u): "Compaction
    /// is at about 1k, so I'll leave the table as it stands rather than edit and re-verify a
    /// README", "Compaction is reporting 0k and I've already spent three commands" — while
    /// compaction is automatic, and that chat compacted at 209,739 tokens and went on.
    Chat(LastCallUsage),
}

thread_local! {
    pub static SKIP: std::cell::Cell<bool> = const { std::cell::Cell::new(false) };
}

pub fn system_prompt_block() -> Option<String> {
    if SKIP.with(|f| f.get()) {
        None
    } else {
        Some(SYSTEM_PROMPT_BLOCK_TEMPLATE.replace("{turn_context_tag}", TURN_CONTEXT_TAG))
    }
}

pub async fn inject_moim(
    session_id: &str,
    conversation: Conversation,
    extension_manager: &ExtensionManager,
    turns_taken: u32,
    max_turns: u32,
    report: ContextReport,
    // Q-94: true = when the request ends on tool results, the block rides in that tool-result
    // message, so a formatter that can join it to the results never renders it as a user turn of
    // its own. false = the swarm's workers, whose golden run was measured with the block in the
    // human message.
    host_on_tool_results: bool,
) -> Conversation {
    if SKIP.with(|f| f.get()) {
        return conversation;
    }

    let session = extension_manager
        .get_context()
        .session_manager
        .get_session(session_id, false)
        .await
        .ok();
    let session_model_config = session
        .as_ref()
        .and_then(|session| session.model_config.clone());
    let context_limit = if let Some(model_config) = session_model_config.as_ref() {
        let provider = extension_manager.get_provider().lock().await.clone();
        match provider {
            Some(provider) => {
                crate::context_mgmt::effective_context_limit(provider.as_ref(), model_config).await
            }
            None => model_config.context_limit,
        }
    } else {
        None
    };
    if should_skip_moim(context_limit) {
        return conversation;
    }

    // Q-266 audit: an unreadable session told the model its folder was "." — goosed's cwd, which
    // since Q-257 is $HOME for every window. The block now says the folder is unknown and why.
    let working_dir = match &session {
        Some(session) => session.working_dir.display().to_string(),
        None => {
            tracing::warn!(
                session_id,
                "turn context: the session record is unreadable, so its folder is unknown"
            );
            "unknown (this chat's session record could not be read)".to_string()
        }
    };
    let total_tokens = session
        .as_ref()
        .and_then(|session| session.usage.total_tokens);
    let compaction_threshold = crate::config::Config::global()
        .get_param::<f64>("GOOSE_AUTO_COMPACT_THRESHOLD")
        .unwrap_or(crate::context_mgmt::DEFAULT_COMPACTION_THRESHOLD);
    let extension_parts = extension_manager.collect_moim_parts(session_id).await;
    let moim = compose_moim(
        &working_dir,
        total_tokens,
        context_limit,
        compaction_threshold,
        turns_taken,
        max_turns,
        extension_parts,
        report,
    );

    let mut messages = conversation.messages().clone();
    let tool_results_tail = messages
        .iter()
        .rposition(|m| m.is_agent_visible())
        .filter(|&last| host_on_tool_results && effective_role(&messages[last]) == "tool");
    if let Some(last) = tool_results_tail {
        messages[last].content.push(MessageContent::text(moim));
    } else {
        let Some(idx) = messages
            .iter()
            .rposition(|m| m.is_agent_visible() && effective_role(m) == "user")
        else {
            return conversation;
        };
        let insert_idx = messages[idx]
            .content
            .iter()
            .take_while(|content| matches!(content, MessageContent::ToolResponse(_)))
            .count();
        messages[idx]
            .content
            .insert(insert_idx, MessageContent::text(moim));
    }

    let (fixed, issues) = fix_conversation(Conversation::new_unvalidated(messages));

    let has_unexpected_issues = issues.iter().any(|issue| {
        !issue.contains("Merged consecutive user messages")
            && !issue.contains("Merged consecutive assistant messages")
            && !issue.contains("Added placeholder to empty tool result")
            && !issue.contains("Trimmed trailing whitespace from assistant message")
            && !issue.contains("Removed trailing assistant message")
            && !issue.contains("Merged text content")
    });

    if has_unexpected_issues {
        tracing::warn!("MOIM injection caused unexpected issues: {:?}", issues);
        return conversation;
    }

    fixed
}

fn should_skip_moim(context_limit: Option<usize>) -> bool {
    context_limit.is_some_and(|limit| limit < MIN_CONTEXT_FOR_MOIM)
}

#[allow(clippy::too_many_arguments)]
fn compose_moim(
    working_dir: &str,
    total_tokens: Option<i32>,
    context_limit: Option<usize>,
    compaction_threshold: f64,
    turns_taken: u32,
    max_turns: u32,
    extension_parts: Vec<String>,
    report: ContextReport,
) -> String {
    let timestamp = chrono::Local::now().format("%Y-%m-%d %H:%M:00");
    let mut lines = vec![
        open_tag(TURN_CONTEXT_TAG),
        tag(CURRENT_TIME_TAG, &timestamp.to_string()),
        tag(WORKING_DIRECTORY_TAG, working_dir),
    ];

    match report {
        // VA-107: a swarm lane reads the two numbers the compaction guard compares, as a fact, in
        // place of a "~Nk tokens remaining" figure relative to a threshold it cannot see — r6h's
        // render-pick lane read "~11k tokens remaining" (from the 128,000 default limit) as its
        // context and compressed its code (receipt on `context_mgmt::context_line`).
        ContextReport::Measured(last_call) => lines.push(context_line(
            last_call,
            total_tokens.map(i64::from),
            context_limit,
        )),
        ContextReport::Chat(last_call) => lines.push(context_line(
            chat_last_call(last_call, total_tokens),
            total_tokens.map(i64::from),
            context_limit,
        )),
        ContextReport::CompactionCountdown => {
            if let Some(value) =
                compaction_remaining_line(total_tokens, context_limit, compaction_threshold)
            {
                lines.push(tag("compaction", &value));
            }
        }
    }
    if let Some(value) = turn_budget_line(turns_taken, max_turns) {
        lines.push(tag("turn-budget", &value));
    }

    for part in extension_parts {
        if !part.trim().is_empty() {
            lines.push(String::new());
            lines.push(part);
        }
    }

    lines.push(close_tag(TURN_CONTEXT_TAG));
    lines.join("\n")
}

fn open_tag(name: &str) -> String {
    format!("<{name}>")
}

fn close_tag(name: &str) -> String {
    format!("</{name}>")
}

fn tag(name: &str, value: &str) -> String {
    format!("<{name}>{}</{name}>", escape_xml_text(value))
}

fn escape_xml_text(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// A chat's session keeps its usage across replies, so a reply's first turn reads the total the
/// previous reply's last call reported (or the count taken after a compaction) — current, not
/// absent. Only a session that never had a total says no call completed.
fn chat_last_call(last_call: LastCallUsage, total_tokens: Option<i32>) -> LastCallUsage {
    match (last_call, total_tokens) {
        (LastCallUsage::NoCallYet, Some(_)) => LastCallUsage::Reported,
        (last_call, _) => last_call,
    }
}

/// Tokens left before the COMPACTION POINT (window × threshold), not before the window ends — kept
/// only for the swarm workers the golden run measured with it (`ContextReport::CompactionCountdown`).
fn compaction_remaining_line(
    total_tokens: Option<i32>,
    context_limit: Option<usize>,
    threshold: f64,
) -> Option<String> {
    let total_tokens = total_tokens?;
    let context_limit = context_limit?;

    if total_tokens <= 0 || context_limit == 0 || threshold <= 0.0 || threshold >= 1.0 {
        return None;
    }

    let compaction_at = (context_limit as f64 * threshold) as i32;
    if compaction_at <= 0 || (total_tokens as f64 / compaction_at as f64) < 0.5 {
        return None;
    }

    Some(format!(
        "~{}k tokens remaining",
        compaction_at.saturating_sub(total_tokens) / 1000
    ))
}

fn turn_budget_line(turns_taken: u32, max_turns: u32) -> Option<String> {
    if max_turns == 0 || turns_taken.saturating_mul(2) < max_turns {
        return None;
    }

    Some(format!("{turns_taken}/{max_turns} used"))
}

#[cfg(test)]
mod chat_context_tests {
    use super::*;

    const WINDOW_3U: usize = 262_144;

    fn chat(total_tokens: Option<i32>, last_call: LastCallUsage) -> String {
        compose_moim(
            "/w",
            total_tokens,
            Some(WINDOW_3U),
            0.8,
            0,
            0,
            vec!["<scratchpad>\nGoal: x\n</scratchpad>".to_string()],
            ContextReport::Chat(last_call),
        )
    }

    /// Q-455, E2E #3u (session 20260928_47, window 262,144, threshold 0.8): the countdown read
    /// "~21k", "~3k" and "~0k tokens remaining" at these totals; the chat now reads what is used.
    #[test]
    fn a_chat_reads_used_of_window_and_no_countdown() {
        for (total, line) in [
            (188_000, "context: 188,000 of 262,144 tokens used (72%)"),
            (206_000, "context: 206,000 of 262,144 tokens used (79%)"),
            (209_739, "context: 209,739 of 262,144 tokens used (80%)"),
        ] {
            let block = chat(Some(total), LastCallUsage::Reported);
            assert!(block.contains(&format!("\n{line}\n")), "{block}");
            assert!(!block.contains("remaining"), "{block}");
            assert!(!block.contains("<compaction>"), "{block}");
            assert!(!block.contains("Compaction"), "{block}");
        }
    }

    /// The reply's first turn: the session's total from the previous reply is current.
    #[test]
    fn a_new_reply_reads_the_sessions_last_total() {
        let block = chat(Some(209_739), LastCallUsage::NoCallYet);
        assert!(
            block.contains("\ncontext: 209,739 of 262,144 tokens used (80%)\n"),
            "{block}"
        );
        let fresh = chat(None, LastCallUsage::NoCallYet);
        assert!(
            fresh.contains("\ncontext: 262,144 tokens window; no call completed yet\n"),
            "{fresh}"
        );
        let silent = chat(Some(209_739), LastCallUsage::NotReported);
        assert!(
            silent.contains(&format!(
                "\n{}\n",
                crate::context_mgmt::context_line::USAGE_UNAVAILABLE_LINE
            )),
            "{silent}"
        );
    }

    /// The countdown stays byte-identical for the swarm workers the golden run measured with it.
    #[test]
    fn the_countdown_is_the_swarm_workers_line_only() {
        let worker = compose_moim(
            "/w",
            Some(209_739),
            Some(WINDOW_3U),
            0.8,
            0,
            0,
            Vec::new(),
            ContextReport::CompactionCountdown,
        );
        assert!(
            worker.contains("<compaction>~0k tokens remaining</compaction>"),
            "{worker}"
        );
        assert!(!worker.contains("\ncontext: "), "{worker}");
    }

    #[test]
    fn the_system_prompt_separates_context_usage_from_the_turn_budget() {
        let block = system_prompt_block().unwrap();
        assert!(!block.contains("compaction status"), "{block}");
        assert!(
            block.contains("Context usage is not a budget for the work."),
            "{block}"
        );
        assert!(
            block.contains("Only `<turn-budget>`, when present, is a signal for how much autonomous work remains."),
            "{block}"
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::conversation::message::Message;
    use rmcp::model::CallToolRequestParams;
    use std::path::PathBuf;

    const CHAT: ContextReport = ContextReport::Chat(LastCallUsage::NoCallYet);

    fn text_at(message: &crate::conversation::message::Message, index: usize) -> &str {
        message.content[index].as_text().unwrap()
    }

    fn is_moim(content: &MessageContent) -> bool {
        content
            .as_text()
            .is_some_and(|text| text.starts_with(&format!("<{}>\n", TURN_CONTEXT_TAG)))
    }

    #[tokio::test]
    async fn test_moim_prepended_to_latest_user_message() {
        let temp_dir = tempfile::tempdir().unwrap();
        let em = ExtensionManager::new_without_provider(temp_dir.path().to_path_buf());
        let session = em
            .get_context()
            .session_manager
            .create_session(
                PathBuf::from("/test/dir"),
                "test".to_string(),
                crate::session::SessionType::User,
                crate::config::GooseMode::Auto,
            )
            .await
            .unwrap();

        let conv = Conversation::new_unvalidated(vec![
            Message::user().with_text("Hello"),
            Message::assistant().with_text("Hi"),
            Message::user().with_text("Bye"),
        ]);
        let result = inject_moim(&session.id, conv, &em, 0, 100, CHAT, false).await;
        let msgs = result.messages();

        assert_eq!(msgs.len(), 3);
        assert_eq!(text_at(&msgs[0], 0), "Hello");
        assert_eq!(text_at(&msgs[1], 0), "Hi");
        assert!(is_moim(&msgs[2].content[0]));
        assert_eq!(text_at(&msgs[2], 1), "Bye");
    }

    #[tokio::test]
    async fn test_moim_injection_no_assistant() {
        let temp_dir = tempfile::tempdir().unwrap();
        let em = ExtensionManager::new_without_provider(temp_dir.path().to_path_buf());
        let session = em
            .get_context()
            .session_manager
            .create_session(
                PathBuf::from("/test/dir"),
                "test".to_string(),
                crate::session::SessionType::User,
                crate::config::GooseMode::Auto,
            )
            .await
            .unwrap();

        let conv = Conversation::new_unvalidated(vec![Message::user().with_text("Hello")]);
        let result = inject_moim(&session.id, conv, &em, 0, 100, CHAT, false).await;

        assert_eq!(result.messages().len(), 1);
        assert!(is_moim(&result.messages()[0].content[0]));
        assert_eq!(text_at(&result.messages()[0], 1), "Hello");
    }

    #[tokio::test]
    async fn test_moim_skips_user_messages_not_visible_to_agent() {
        let temp_dir = tempfile::tempdir().unwrap();
        let em = ExtensionManager::new_without_provider(temp_dir.path().to_path_buf());
        let session = em
            .get_context()
            .session_manager
            .create_session(
                PathBuf::from("/test/dir"),
                "test".to_string(),
                crate::session::SessionType::User,
                crate::config::GooseMode::Auto,
            )
            .await
            .unwrap();

        let conv = Conversation::new_unvalidated(vec![
            Message::user().with_text("agent visible"),
            Message::assistant().with_text("reply"),
            Message::user().with_text("user only").user_only(),
        ]);
        let result = inject_moim(&session.id, conv, &em, 0, 100, CHAT, false).await;
        let msgs = result.messages();

        assert_eq!(msgs.len(), 2);
        assert!(is_moim(&msgs[0].content[0]));
        assert_eq!(text_at(&msgs[0], 1), "agent visible");
        assert_eq!(text_at(&msgs[1], 0), "user only");
        assert!(!msgs[1].is_agent_visible());
    }

    #[tokio::test]
    async fn test_moim_with_tool_calls() {
        let temp_dir = tempfile::tempdir().unwrap();
        let em = ExtensionManager::new_without_provider(temp_dir.path().to_path_buf());
        let session = em
            .get_context()
            .session_manager
            .create_session(
                PathBuf::from("/test/dir"),
                "test".to_string(),
                crate::session::SessionType::User,
                crate::config::GooseMode::Auto,
            )
            .await
            .unwrap();

        let conv = Conversation::new_unvalidated(vec![
            Message::user().with_text("Search for something"),
            Message::assistant()
                .with_text("I'll search for you")
                .with_tool_request("search_1", Ok(CallToolRequestParams::new("search"))),
            Message::user()
                .with_tool_response("search_1", Ok(rmcp::model::CallToolResult::success(vec![]))),
        ]);

        let result = inject_moim(&session.id, conv, &em, 0, 100, CHAT, false).await;
        let msgs = result.messages();

        assert_eq!(msgs.len(), 3);
        assert!(is_moim(&msgs[0].content[0]));
        assert_eq!(text_at(&msgs[0], 1), "Search for something");
        assert!(matches!(
            &msgs[2].content[0],
            MessageContent::ToolResponse(_)
        ));
        assert_eq!(msgs[2].content.len(), 1);
    }

    /// Q-94: a chat agent whose request ends on tool results hosts the block in that tool-result
    /// message (the formatter joins it to the results); a request ending on the user's own words,
    /// and every swarm worker, keep it in the human message.
    #[tokio::test]
    async fn chat_hosts_the_block_on_a_tool_results_tail() {
        let temp_dir = tempfile::tempdir().unwrap();
        let em = ExtensionManager::new_without_provider(temp_dir.path().to_path_buf());
        let session = em
            .get_context()
            .session_manager
            .create_session(
                PathBuf::from("/test/dir"),
                "test".to_string(),
                crate::session::SessionType::User,
                crate::config::GooseMode::Auto,
            )
            .await
            .unwrap();
        let tool_tail = || {
            Conversation::new_unvalidated(vec![
                Message::user().with_text("How long can they stay on Data Center?"),
                Message::assistant()
                    .with_text("Answered.")
                    .with_tool_request("k1", Ok(CallToolRequestParams::new("propose_knowledge"))),
                Message::user()
                    .with_tool_response("k1", Ok(rmcp::model::CallToolResult::success(vec![]))),
            ])
        };

        let chat = inject_moim(&session.id, tool_tail(), &em, 0, 100, CHAT, true).await;
        let msgs = chat.messages();
        assert_eq!(msgs.len(), 3);
        assert_eq!(msgs[0].content.len(), 1, "the question stays as asked");
        assert!(matches!(
            msgs[2].content[0],
            MessageContent::ToolResponse(_)
        ));
        assert!(is_moim(msgs[2].content.last().unwrap()));

        let swarm = inject_moim(
            &session.id,
            tool_tail(),
            &em,
            0,
            100,
            ContextReport::CompactionCountdown,
            false,
        )
        .await;
        assert!(is_moim(&swarm.messages()[0].content[0]));
        assert_eq!(swarm.messages()[2].content.len(), 1);

        let asked = Conversation::new_unvalidated(vec![Message::user().with_text("Bye")]);
        let asked = inject_moim(&session.id, asked, &em, 0, 100, CHAT, true).await;
        assert!(is_moim(&asked.messages()[0].content[0]));
    }

    /// The turn-context block is produced here (`compose_moim`, in goose) but
    /// recognized in a different crate (`is_turn_context_text`, in
    /// goose-providers) by matching its textual shape. That recognition is the
    /// only thing that keeps the volatile block out of the Anthropic cache
    /// prefix. The two are coupled by string layout alone, with no shared type
    /// or compiler check, so a reorder or rename on either side would silently
    /// collapse prompt caching. These tests fail loudly if they drift apart.
    mod turn_context_detector_coupling {
        use super::*;
        use crate::conversation::is_turn_context_text;

        fn moim(
            total_tokens: Option<i32>,
            context_limit: Option<usize>,
            turns_taken: u32,
            max_turns: u32,
            extension_parts: Vec<String>,
            report: ContextReport,
        ) -> String {
            compose_moim(
                "/Users/me/code/goose",
                total_tokens,
                context_limit,
                0.8,
                turns_taken,
                max_turns,
                extension_parts,
                report,
            )
        }

        /// VA-107: measured mode carries the guard's two numbers as a fact and no
        /// "~Nk tokens remaining" line; the block stays a turn-context block to the anthropic
        /// relocator. The swarm worker's countdown at r6h's numbers is the exact figure the lane
        /// read.
        #[test]
        fn measured_context_line_replaces_the_compaction_remaining_figure() {
            let block = compose_moim(
                "/Users/me/code/goose",
                Some(90_821),
                Some(180_224),
                0.8,
                7,
                0,
                Vec::new(),
                ContextReport::Measured(LastCallUsage::Reported),
            );
            assert!(
                block.contains("\ncontext: 90,821 of 180,224 tokens used (50%)\n"),
                "{block}"
            );
            assert!(!block.contains("<compaction>"), "{block}");
            assert!(is_turn_context_text(&block), "{block}");
            let classic = compose_moim(
                "/x",
                Some(90_821),
                Some(128_000),
                0.8,
                7,
                0,
                Vec::new(),
                ContextReport::CompactionCountdown,
            );
            assert!(
                classic.contains("<compaction>~11k tokens remaining</compaction>"),
                "{classic}"
            );
        }

        #[test]
        fn compose_moim_output_is_recognized_by_the_anthropic_detector() {
            let guardrail = || vec!["<guardrail>stay on task</guardrail>".to_string()];
            let chat = ContextReport::Chat(LastCallUsage::Reported);
            let countdown = ContextReport::CompactionCountdown;
            let cases = [
                ("minimal", moim(None, None, 0, 0, vec![], countdown)),
                (
                    "with a chat's context line",
                    moim(Some(100_000), Some(200_000), 0, 0, vec![], chat),
                ),
                (
                    "with a worker's compaction line",
                    moim(Some(100_000), Some(200_000), 0, 0, vec![], countdown),
                ),
                (
                    "with turn-budget line",
                    moim(None, None, 20, 40, vec![], countdown),
                ),
                (
                    "with extension context",
                    moim(None, None, 0, 0, guardrail(), chat),
                ),
                (
                    "fully populated",
                    moim(Some(100_000), Some(200_000), 20, 40, guardrail(), chat),
                ),
            ];

            for (label, block) in &cases {
                assert!(
                    is_turn_context_text(block),
                    "is_turn_context_text rejected real compose_moim output ({label}); the \
                     producer in goose and the detector in goose-providers have drifted, so the \
                     volatile block will no longer be kept out of the Anthropic cache prefix:\n\
                     {block}"
                );
            }
        }

        #[test]
        fn detector_rejects_text_that_is_not_a_turn_context_block() {
            assert!(
                !is_turn_context_text("Please refactor the argument parser."),
                "ordinary user text must not be treated as a turn-context block"
            );
            assert!(
                !is_turn_context_text(
                    "<turn-context>\n\
                     <current-time>2026-06-25 12:00:00</current-time>\n\
                     <session-id>abc</session-id>\n\
                     </turn-context>"
                ),
                "a block whose first field after current-time is not working-directory must not \
                 match: the detector's shape checks are what discriminate the injected block"
            );
        }
    }
}
